src/s3_ccdi_to_tabbreakery.py
- The bug in tabbreaker removed any column with a name ends with `_id`. The modified code only drops any column with a name follows `[node].[node]_id` pattern
=> fixed a bug in tabbreaker

src/read_buckets.py, src/utils.py
Added Features
- The prefect artifact key only allows lowercase letter, number and dash. As the artifact key includes runner id as part of the key, the change replaces all the space ` `, dot `.` and underscore `_` in the runner id with dash `-`
=> Fix runner id key error

src/read_buckets.py, tests/test_read_buckets.py
Added Features
- Bucket reader now allows reading into bucket subdirectories
- Bucket reader now recognizes secondary file extension for compressed files (`.gz` and `.zip`)
=> Ccdidc 789 bucket subdirectory

src/s3_ccdi_to_sra.py
Added Features to SRA subflow
- All unmatched library source, strategy, and selection values will be converted to `OTHER` or `other`
- `Unknown` instrument model for `ION_TORRENT` platform will be converted to `unspecified`
=> Ccdidc 809 hard code sra value

prefect.yaml, src/file_mover.py, src/utils.py, tests/test_file_mover.py, workflows/File_Mover.py
Added Features
- Added new workflow `file-mover` which takes CCDI manifest and destination bucket folder path as input and copys file objects from the staging bucket to the destination bucket path. The workflow performs md5sum check before and after file copying.
- The workflow produces 3 outputs: `new CCDI manifest with modified bucket urls`, `logging file`, and `a file transferring summary table tsv`.
=> Ccdidc 791 file mover

src/s3_catcherry.py, src/s3_ccdi_to_cds.py, src/template_exampler.py, src/update_ccdi_template.py
Quick Fix
- Maintain the `header style` when re-writing dataframe to excel sheet
- Affected codes: s3_catcherry.py, template_exampler.py, update_ccdi_template.py
=> Ccdidc 859 keep header style

src/utils.py, tests/test_utils.py, workflows/s3-Prefect-Pipeline.py
- Allows `ccdi-data-curation` workflow to continue even when github api fails due to api rate limit reached
=> allows workflow to conitnue without latest template version info

requirements.txt, src/create_submission.py, src/s3_ccdi_to_cds.py, src/utils.py
Added patch
- Make github api calls with headers info including a credential token
- Changes made to workflows: `ccdi-data-curation`, `model-to-submission`
=> CCDIDC-914 Make github API call with token headers

src/utils.py
New patch captures `NotADirectoryError` during folder downloading
=> CCDIDC-952 folder downloading error fixing 

prefect.yaml, requirements.txt, src/file_mover.py, src/file_remover.py, src/read_buckets.py, src/utils.py, tests/test_file_remover.py, workflows/File_Remover.py
- Added interactive `file_remover` workflow. User can start the workflow with a tsv manifest which contains a column of s3 uri to be deleted, or without manifest. When running without manifest, user need to provide a production bucket path and a staging bucket path, and the workflow will try to find object match between two locations. 
- Added unittests for `file_remover`
=> Ccdidc 886 file remover

src/s3_ccdi_to_sra.py
- Allows SRA script to filter obj files based on `filetype` before property value validation. This changes gives a cleaner and shorter SRA logging report
=> Ccdidc 1092 sra filter filetypes

src/read_buckets.py, tests/test_read_buckets.py
- Enforce the `Prefix` of `paginate_parameter` to end with `/`
=> CCDIDC-1094 bucket reader bug

src/utils.py, workflows/dcf_indexing.py
Added Improvement
- The workflow now adds new guids to any file objects with missing `dcf_indexd_guid` value in excel spreadsheet
- If objects with missing guid is found, the workflow produces two outputs, one is `the modified manifest with filled new guids`, and the other is `dcf index tsv file`. If no missing guids were identified in the manifest, the workflow only generates `dcf index tsv` file
=> CCDIDC-1148 add missing guid

prefect.yaml, src/file_mover.py, src/file_remover.py, src/s3_catcherry.py, src/s3_ccdi_to_cds.py, src/s3_ccdi_to_index.py, src/s3_ccdi_to_sra.py, src/s3_validationry.py, src/s3_validationry_refactored.py, src/template_exampler.py, src/utils.py, tests/test_file_mover.py, tests/test_utils.py, tests/test_validationry_refactored.py, workflows/guid_checker.py, workflows/mci_release_run.py
The main edits were replacing the phrase "file_url_in_cds" with just "file_url", except in cases where there was a lift-over to CDS and the property is still called "file_url_in_cds".
=> 1.9.0 fixes

src/utils.py, tests/test_utils.py, workflows/dcf_indexing.py
Added Feature
- Pipeline was modified to accommodate the new `acl` and `authz` at file level instead of study level.
- The pipeline now only works for model version 1.8.0 and above, since `file level acl and authz` were missing before that version
=> CCDIDC-1206 dcf index update

src/s3_catcherry.py, src/s3_validationry_refactored.py
Added Patch
- Added a new section in Catcherry which walks through all string type columns in a dict of df and replaces any no-break space with whitespace.
=> CCDIDC-1259 no break space removal

src/s3_validationry_refactored.py, tests/test_validationry_refactored.py
Fixed bug
- The bug was caused by the failure of subsetting`Dictionary` dataframe using `Key` value == True. The fix is to convert the value to uppercase and force the selected value to be `TRUE`
- Both validations of `unique key` and `key id`  were modified, as well as unittests
=> CCDIDC 1266 validation key id bug

src/join_tsv_to_manifest.py
Added patch 
- Keep `id` and `<node>.id` value in the manifest output
=> CCDIDC-1311 keep the id content in joinry

prefect.yaml, src/s3_ccdi_to_sra.py
Added patch
- Create new library id when more than one active location urls associated with the same library id were found
- new library id would be [old_library_id]_[number]
=> CCDIDC-1334 SRA: create new library id when multiple active location URLs are found

src/file_mover.py
Changes:
- More logging, that way we can understand where exactly the problem occurred.
- A time.sleep(0.25) between each task/flow submission to slow down the number of consecutive hits to the Prefect API. This should help reduce the "Key Errors" we often see.
- For V3, add NO_CACHE policy to tasks run concurrently as well to handle pickle/serialization errors related to passing logger and other objects to concurrency pools
- Edited naming schema of intermediate md5sum check files so that results across different days of run are appended to same file/ 1 file is produced.
=> CCDIDC-1688

prefect.yaml, src/gdc_utils.py, workflows/gdc_file_upload.py
Updates in PR include: 
- Removing reliance on indexd to find file locations and instead taking input manifest that has this information
- Querying GDC Submission API to find associated UUIDs for files, requiring node_type of files as input to workflow
- Perform UUID matching by matching on file_name, file_size and md5sum
- Filtering out files in manifest that were either already uploaded and validated or not found to have metadata submitted to GDC graph
- Saving filtered out files in manifest to additional output files
- added new workflow option 'check_status' to check GDC API status and add in any test statements if needed
- Add intermediate file output after each chunk is uploaded for handling in case of workflow crash for long runs
-  Adding gdc_utils.py with functions for querying …
=> CCDIDC 1644 gdc upload

prefect.yaml, src/file_mover.py, workflows/file_mover_delete.py
Fixing errors in file_mover_delete.py that is causing file-mover-v3 to crash:
- handling extra returned object from one function
- handling of logger object passed to one of the flows
- chunking inputs to flow objects 
Also:
- added efficiency via concurrency in file copying and md5sum checks
- added new specification of concurrency pool to avoid competition for resources  between different, simultaneous runs
=> CCDIDC-1739  File mover error

workflows/file_mover_delete.py
Added feature
- Added a more generic file mover pipeline that takes a tsv file as input which contains original s3 uri and destination s3 uri
- This workflow covers broader use cases such as, runner wants files to be moved to different folder locations, runner doesn't want to preserve original folder structure
=> CCDIDC-1738 generic file mover pipeline
