CBIIT/ChildhoodCancerDataInitiative-Prefect_Pipeline

prefect.yaml, src/s3_catcherry.py
Fixed a bug while reading excel sheet in `s3_catcherry.py`
=> fixed a bug in catcherr

src/s3_catcherry.py
skip `<NA>`  while modifying column values during s3_chatcherr
=> fixed s3_catcherry bug of handling missing value

src/s3_ccdi_to_sra.py
Avoid sys.exit() during CCDI_to_SRA conversion if no sequencing files were found in manifest or no row of sequencing file passed verification process.
=> fixed sys exit bug in sra script

s3-Prefect-Pipeline.py, src/s3_ccdi_to_tabbreakery.py, src/utils.py
- Added TabBreaker step in the workflow
- Allowed uploading TabBreaker outputs to the bucket
- Modified output markdown to include TabBreaker outputs
=> Add tabbreaker

prefect.yaml, src/s3_validationry.py
Commented out a logic path that a template should never go down.
Fixed the columns selected for cross node validation.
Deleted the df_bucket at the end of the section to alleviate memory usage.
=> Validationry testing

prefect.yaml, src/update_ccdi_template.py, src/utils.py, workflows/Template_Updater.py, workflows/s3-Prefect-Pipeline.py
- Reorganize all workflows under `./workflows` folder
- Added `Template_Updater.py` workflow 
- Added try except block which allows fail of subflow without loosing every outputs
=> CCDIDC-741 Add updater workflow

prefect.yaml, src/s3_ccdi_to_cds.py, src/s3_ccdi_to_index.py
=> CCDIDC-757

requirements.txt, src/utils.py, tests/test_template_updater.py
- Added unittests for update_ccdi_template.py
- Fixed a string search related minor bug in utils.py
=> CCDIDC-750 added unittests for update_ccdi_template.py

src/s3_ccdi_to_index.py, src/s3_validationry.py, src/utils.py, workflows/s3-Prefect-Pipeline.py
- `ccdi-data-curation` workflow now allows subflow fail while still keeps and uploads the outputs of the rest workflow in the bucket 
- Workflow outputs markdown function has been changed that allows missing outputs
=> CCDIDC-746 allow subflow fail

src/s3_ccdi_to_sra.py
Fixed an SRA subflow bug that causes prolonged run time.
=> fixed an sra subflow bug

src/read_buckets.py, src/utils.py
Allows runner id that contains forward slash (`/`) symbol
=> Allow runner id slash

prefect.yaml, requirements.txt, src/template_exampler.py, src/utils.py, tests/test_template_exampler.py, tests/test_utils.py, workflows/Template_Exampler.py
Added Features
- Added template exampler workflow
- Added unit tests for template exampler
=> Ccdidc 770 template exampler

src/s3_ccdi_to_sra.py
Added Features in CCDI_to_SRA
- For files sharing the same library ID, sort the files based on the completeness of the sequencing metadata (bases, reads etc) and filetype
=> CCDIDC-813 resort files sharing the same library ID

src/utils.py, workflows/s3-Prefect-Pipeline.py
Added Features
- Workflow now allows inputs of SRA previous submission files and dbGaP previous submission folder
=> Ccdidc 790 add pre sra dbgap input

prefect.yaml, src/s3_ccdi_to_cds.py, src/s3_ccdi_to_index.py
Ccdidc 747
When there are no files, gracefully quit the CCDI_to_CDS/Index scripts with no file and a log file that notes it is missing data files.
=> Ccdidc 747

src/s3_ccdi_to_sra.py
Added Features
- If `reference genome assembly` or `alignment software` is missing for aligned data ["cram", "crai", "bam", "bai"], assign a value of `Not Reported`
- Library_IDs that are associated with same sample_ID and sharing the same library strategy, selection, and source, are combined into a single line by concatenating library_IDs, design_description, reference genome assembly, alignment software, and active location urls
- Replace invalid characters with valid characters for column `alignment software`
=> CCDIDC-822 SRA bug fix

src/s3_ccdi_to_sra.py
Bug Fix
- Avoid workflow fail when `software_alignment` value is missing (`np.nan`)
=> CCDIDC-833 fixed ccdi to sra bug, alignment software str replacement

src/s3_ccdi_to_sra.py
Bug Fix
- Avoid concatenating `np.nan` when joining items from list
=> fixed a bug ccdi_to_sra, function concatenate_library_id

src/s3_ccdi_to_sra.py, workflows/s3-Prefect-Pipeline.py
Added Feature
- Added study contact information to the front sheet of SRA submission file
=> Ccdidc 850 add sra contact

src/create_submission.py, src/template_exampler.py, src/utils.py, tests/test_model_to_manifest.py, workflows/model_to_submission.py, workflows/new_model_validation.py
**Added Feature**
- Added new workflow of `model-to-submission` which creates CCDI submission template by using model files(ccdi-model.yml, terms.yaml, and ccdi-model-props.yml from [ccdi-model repo](https://github.com/CBIIT/ccdi-model/tree/main/model-desc))
- Added new workflow of `new-model-validation`, which contains 3 subflows, model-to-submission, template-exampler, and validationRy 
- Unittests associated with model-to-submission were added
=> Ccdidc 792 model to submission

prefect.yaml, requirements.txt, src/neo4j_data_tools.py, src/utils.py, tests/test_neo4j_data_tools.py, workflows/bucket_reader.py, workflows/get_s3_parameter.py, workflows/pull_neo4j_data.py, workflows/validate_neo4j_data.py
Added Features
- Added workflow `workflows/pull_neo4j_data.py`, which generates tsv files of each node for all studies in neo4j DB
- Added workflow `workflows/validate_neo4j_data.py` which validates the data entry `counts and ids` in every node of every study in neo4jDB against ingestion files located in a s3 bucket
- Both workflows utilize concurrent task running, cutting workflow running time
- Unittests have been added
=> CCDIDC-861 CCDIDC-862 pulling neo4j data and validation

prefect.yaml
setup deployments with different memory levels or specific memory levels.
=> memory_levels

prefect.yaml, src/neo4j_data_tools.py
Added Patch
- Avoid oversized dataframe as input for the flow of concurrency task running
=> Neo4j validate patch

src/utils.py
- Added error message when github API reaches limit while downloading template
=> Added error message 

src/s3_ccdi_to_dbgap.py
Changed made
- Read previous submission files as `str` dtype for all columns
=> CCDIDC-901  Remove duplicates in dbgap output

src/s3_ccdi_to_sra.py
- Reformat  `Illumina NextSeq 2000` and `Illumina NextSeq 1000` into `NextSeq 2000` and `NextSeq 1000`, respectively
=> reformat sra instrument model value

src/utils.py, tests/test_utils.py, workflows/dcf_indexing.py
Added a new workflow that generates DCF index file from CCDI multisheets Excel file (.xlsx)
=> Ccdidc 948 dcf indexing

src/submission_cruncher.py, workflows/Submission_Cruncher.py
Added new workflow of merging submission files (xlsx files) into a single CCDI manifest file (xlsx)
=> Ccdidc 915 submission cruncher

requirements.txt, src/join_tsv_to_manifest.py, src/utils.py, tests/test_join_tsv_to_manifest.py, workflows/db_tsv_to_manifest.py
- Added a workflow joining `tabbreaker` outputs/`pull_neo4j_db` outputs back into ccdi manifest
- Added unittests of the workflow
=> Ccdidc 964 join tsvs

src/s3_ccdi_to_cds.py, src/s3_ccdi_to_dbgap.py, src/s3_ccdi_to_index.py, src/s3_ccdi_to_tabbreakery.py
- Avoids file not found error from running overnight flows
=> Overnight flow bug

prefect.yaml, workflows/guid_checker.py
=> Guid checker, CCDIDC-956

src/create_submission.py, workflows/model_to_submission.py
- Modified outdated preferred sheets order
- Added try except block for easier troubleshooting in the future
=> Modify hard coded sheet order

src/file_remover.py
- Removed concurrently task running flows and replace them with loop
=> CCDIDC-1115 file remover bug

src/neo4j_data_tools.py
Fix to acl, where `['` and `']` were being removed.
=> Fix to acl

src/file_remover.py
Fixed bug
- Removed flow and task decorator for some flows that takes up resource of prefect. Instead replace with simple loop.
=> CCDIDC 1115 file remover bug

src/mci_monthly_release.py, workflows/mci_release_run.py
Added Feature
- Added new workflow to streamline the MCI monthly release process
- The workflow scans the staging folder and finds newly added CCDI manifest compared to a previous pull list, and then combines them into a single manifest
=> CCDIDC-1144 mci prefect

src/s3_ccdi_to_sra.py, src/utils.py, workflows/s3-Prefect-Pipeline.py
Added Feature
- Removed the `CCDI to Index` module in ccdi-data-curation pipeline which generates the manifest for Velsera
- Added a flow in `src/utils.py` which takes ccdi manifest as input and returns a dcf index manifest. Added this flow to the ccdi-data-curation pipeline
- Fixed a bug in `src/s3_ccdi_to_sra.py` that caused KeyError
=> CCDIDC-1186 ccdi curation update

src/read_buckets.py, src/utils.py, workflows/fetch_size_md5sum.py
Added Feature
- Allows users to choose s3 bucket path or s3 object uri to fetch object size and fetch
- Allows user to put one or more s3 bucket paths to fetch size and md5sum of all objects under
=> CCDIDC 1139 dir level size md5sum

src/s3_validationry_refactored.py
Fixed a minor bug
- Revised code to avoid problematic iteration during terms and value sets validation.
=> CCDIDC 1254 validation report error

src/s3_ccdi_to_sra.py, workflows/ccdi_to_sra.py
Added enhancement
- New modification added to `ccdi_to_sra` script that changes filename, making sure the filename is unique across the submission file
=> CCDIDC 1253 sra duplicated filename fix

requirements.txt, src/sra_metadata.py
Added feature
- Added workflow that extracts metadata of sequencing files that is required in SRA submission
=> CCDIDC-1166 sra metadata

src/s3_catcherry.py
Added Patch
- The `None` value under `relationship` property under `family_relationship` node was read as NA value by pandas. A fix was added accordingly.
=> CCDIDC-1298 catcherry fail

src/neo4j_data_tools.py
Added patch
- Fix a bug which causes a flow to fail when the provided tsv folder has a node file that is not present in the DB
- Modified cypher query which speeds up the search
=> CCDIDC-1301 neo4j bug

prefect.yaml
What is changed
- Updated `prefect.yaml` file which covers the configuration of deployments in Prefect Cloud
=> Updated prefect yaml 

prefect.yaml, workflows/File_Mover.py, workflows/File_Remover.py, workflows/Submission_Cruncher.py, workflows/Template_Exampler.py, workflows/bucket_reader.py, workflows/ccdi_manifest_liftover.py, workflows/db_tsv_to_manifest.py, workflows/dcf_indexing.py, workflows/fetch_size_md5sum.py, workflows/mci_release_run.py, workflows/model_to_submission.py, workflows/new_model_validation.py, workflows/pull_neo4j_data.py, workflows/s3-Prefect-Pipeline.py, workflows/validate_neo4j_data.py
Added patch
- Added docstring to the workflow entrypoint
- The deployment in Prefect now shows parameter instruction
=> CCDIDC-1300 Added docstring to workflow entries

prefect.yaml
Updated deployments configuration prefect.yaml file
=> CCDIDC-1300 updated deployments configuration

prefect.yaml, workflows/file_mover_delete.py, workflows/mci_file_mover.py
Added Pipeline
- Added a pipeline that copies a list of uri (can be either s3 object or directory) to a new folder (same bucket), and removes the copies at the original location.
- Performs md5sum check before obj deletion
=> CCDIDC-1314 mci mover

src/s3_validationry_refactored.py
Added  patch
- Added additional item of validation for non-unique key id across the entire manifest
- Report any duplicated id values within node or across nodes
=> Ccdidc 1317 add key id validation

src/s3_ccdi_to_sra.py
Introduce new catch if statement for the dbGaP accession to determine ACL for workflow.
=> CCDIDC-1322

src/s3_ccdi_to_sra.py, workflows/s3-Prefect-Pipeline.py
Added patch
- Allows SRA script to read acl from manifest correctly
=> SRA acl bug

src/s3_catcherry.py
added patch
- Fix the error caused by duplicated rows in catcherry script
=> CCDIDC-1336 catcherry bug after 

src/create_submission.py, tests/test_model_to_manifest.py
Added patch
-  Fixed create_submission.py due to the changes in CCDI data model to comply with the bento-mdf schema json
- Modified unittest accordingly
=> CCDIDC-1332 create submission fix

prefect.yaml, src/s3_validationry_refactored.py
Add check for ages 90 years or more in days.
=> CCDIDC-558_age_validation

src/utils.py, workflows/fetch_size_md5sum.py
Improvements
- Allows fetch_size_md5sum to accept file containing s3 uri as input
- Added pull down list in deployment
=> CCDIDC 1352 fetch size md5sum enhancement

src/create_submission.py, workflows/new_model_validation.py
Added patch
- Fixed the bug in new model validation pipeline
=> CCDIDC-1354 fix new model validation

src/s3_ccdi_to_tabbreakery.py
Added changes
- Use uuid.uuid5 to generate a uuid str from a given string, `<phs_id>`::`<node_name>`::`<key_property_value>`
- `<phs_id>` is derived from `dbgap_accession` value from `study` node
=> CCDIDC-1318 tabbreaker new

src/join_tsv_to_manifest.py
Added patch
- Modified JoinRy script to accommodate the recent changes to tab breaker (new id generated through uuid5)
=> CCDIDC-1362 joinry rework

src/sandbox_indexd_guid_validation.py
Added feature
- Added a new workflow of guid validation between neo4j sandbox DB and indexd record
=> CCDIDC-1267 guid meta check

src/file_mover.py, src/file_remover.py
Added patch
- Avoid same file coping in file-mover
- Remove duplicated uri in file-remover to avoid object not exist error
=> CCDIDC-1380 file remover bug

src/template_exampler.py, tests/test_template_exampler.py
Added patch
- limited random integer for age properties between the range of [0, 32849] (by day)
=> CCDIDC-1376 generate random number for age property

src/s3_ccdi_to_dbgap.py, workflows/s3-Prefect-Pipeline.py
added patch
- remove any synonym from dbgap in dbgap submission file subflow
=> CCDIDC-1377 dbgap subflow update

src/file_mover.py
Fixed bug
- Fixed a bug caused by dropping duplicates of a df with a column of dictionary type
=> CCDIDC-1446 file copier bug

src/join_tsv_to_manifest.py, src/neo4j_data_tools.py, workflows/pull_neo4j_data.py
Added patch
- Fix a bug of db export to tsv due to the change of id value from human readable string to uuid5
- Fix a bug of join tsv back to manfest workflow
=> CCDIDC-1442 export neo4j data bug

src/neo4j_data_tools.py
Added patch
- fix a bug in db validation against tsv due to the change of id from human readable str to uuid5
=> CCDIDC-1433 changed how to parse study id from tsv file

workflows/File_Remover.py
Added patch
- Added dropdown list to the file_remover flow
=> CCDIDC-1447 added dropdown list to file remover flow

prefect.yaml, src/neo4j_data_tools.py
Added workflow
- Added a flow which takes a dataframe containing node names and property names, and pulls the unique values of these properties from sandbox neo4j DB. The flow further parses the unique values into unique items if the property is found as list type (based off latest tagged manifest).
- The purpose of this flow is to report the unique terms for certain properties that has a facet selection filter in FE. The report of this flow can be used for QA team for quality check purpose.
=> CCDIDC-1455 ccdi portal report

src/file_mover.py, workflows/file_mover_delete.py
Added patch
- Allows bucket name (only) to be the destination location
=> CCDIDC-1503 file mover bug

src/utils.py
=> CCDIDC-1521

prefect.yaml, src/search_bucket_content.py
Added workflow
- Added a workflow which searches for text in object key path of certain buckets
- Returns an output in json format
=> CCDIDC-1510 bucket search

src/s3_ccdi_to_dbgap.py, src/s3_ccdi_to_sra.py
Added Patch
- Avoid alternative library_id naming during SRA submission if multiple s3 bucket location is found
- Find participant sample mapping for samples derived from pdx/cell_line (CCDIDC-1529)
=> CCDIDC-1526 pivot sra debug

src/neo4j_data_tools.py, workflows/neo4j_db_diff.py
Added workflow
- Added a workflow that generates a report on the diffs between CCDI sandbox and DEV tier DB instances
=> CCDIDC-1448 neo4j diff

src/s3_ccdi_to_dbgap.py, workflows/s3-Prefect-Pipeline.py
Fixed bug
- Fixed a bug that finds the participant and sample id through the route of `participent <- sample <- [cell_line/pdx] <- sample` while generating dbgap sample subject submission file.
- Report any reciprocal loop error
=> CCDIDC-1590 ccdi to dbgap bug

prefect.yaml, src/mci_monthly_release.py, workflows/mci_release_run.py
Fixed bug
- Fixed a bug caused by large input parameter for a prefect flow
=> CCDIDC-1608 mci release manifest bug

prefect.yaml, src/file_mover.py
Increasing large file copying efficiency
=> Ccdidc 1636 concurrent file mover

.gitignore, src/c3dc_json_to_tsv.py
Removed foreign IDs from UUID generation for participants and reference files.
=> C3DC UUID Fix

prefect.yaml, src/neo4j_data_tools.py
Fixed bug
- Fixed the task concurrency running bug occurred in two workflows: `pull-neo4j-data` and `validate-neo4j-data`
=> CCDIDC-1704 validate db bug

src/file_remover.py
Added patch
- added no cache policy to get_md5sum task
=> Update file_remover.py for a bug

prefect.yaml, workflows/cpi_api_return.py
Added patch
- Minor changes made so the code is compatible with Prefect v3 work pool
- Added new deployment config for CCDI CPI API workflow
=> CCDIDC-1754 CCDI CPI API return V3

prefect.yaml, src/neo4j_data_tools.py, workflows/pull_neo4j_data.py
We have the ability to download all data from our database; We need to capability that does this task but only for a given study phs_id.
=> Ccdidc 1895 neo pull
